#!/bin/bash
rm otp_enc
rm otp_enc_d
rm otp_dec
rm otp_dec_d
rm keygen

gcc -std=c99 -o otp_enc_d otp_enc_d.c
gcc  -o otp_enc otp_enc.c 
gcc -std=c99 -o keygen keygen.c
gcc  -o otp_dec otp_dec.c
gcc -std=c99 -o otp_dec_d otp_dec_d.c
